### ISSUE TITLE
Crash during OAuth authorization

### ISSUE THREAD

**Issue by AtomCrafty** [zeppaman/GitStats#1]
After authorizing the via the GitHub OAuth interface it always displays this error:
```
One or more errors occurred. 
  at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
  at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
  at System.Threading.Tasks.Task`1.get_Result()
  at GitHubStats.Controllers.OAuthController.Authorize(String code, String state)
  in D:\temp\4mdehpvm.aei\input\GitHubStats\Controllers\OAuthController.cs:line 61
```

**Comment by PCAssistSoftware** [comment]
@zeppaman - just got same error as above
